"""
COS Brain — Knowledge Engine.

Converts completed reasoning threads into structured long-term memory.
This simulates human memory consolidation.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional
import uuid


@dataclass
class KnowledgeEntry:
    """A consolidated knowledge record from a completed thread."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    user_id: str = ""
    problem: str = ""
    sources: list[str] = field(default_factory=list)
    conclusion: str = ""
    thread_id: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.utcnow)


class KnowledgeEngine:
    """
    Manages long-term knowledge memory.

    When a reasoning thread completes, it is distilled into a knowledge record:
    - Problem: what was the user trying to solve?
    - Sources: which pages did they visit?
    - Conclusion: what did they learn?
    """

    def extract_knowledge_from_thread(
        self,
        thread_title: str,
        capsule_titles: list[str],
        capsule_urls: list[str],
        thread_summary: str = None,
    ) -> KnowledgeEntry:
        """
        Build a knowledge record from a completed thread's data.
        In production, the conclusion would be generated by an LLM.
        """
        problem = thread_title or "Unknown research topic"
        sources = list(set(capsule_urls))[:10]  # Deduplicate, cap at 10
        conclusion = thread_summary or self._extract_conclusion(capsule_titles)

        return KnowledgeEntry(
            problem=problem,
            sources=sources,
            conclusion=conclusion,
        )

    def _extract_conclusion(self, titles: list[str]) -> str:
        """Fallback conclusion extraction from capsule titles."""
        if not titles:
            return "No conclusion extracted."
        # Use the most unique words as a summary
        all_words = " ".join(titles)
        return f"Research covering: {all_words[:200]}"
